name: Deploy on VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | sed 's/\\n/\n/g' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: ğŸ” Debug SSH Key
        run: |
          echo "Checking contents of ~/.ssh directory:"
          ls -la ~/.ssh

          echo "Trying SSH connection..."
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo âœ… Connected Successfully"

      - name: ğŸš€ Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            set -x

            cd /jobs-portal
            git pull

            cd /jobdedo-frontend
            npm install
            npm run build

            cd ../jobdedo-backend
            npm install
            npm run build

            cd ..
            pm2 restart ecosystem.config.js
          EOF
